# Convolution

## Linear Time-Invariant (LTI) Systems

:::: {.columns}
::: {.column style="width:fit-content;"}
```{.tikz}
\begin{tikzpicture}[>=latex, thick]
  \node[draw, minimum width=2.2cm, minimum height=1cm] (sys) {$LTI$};

  \draw[->] (-3,0) -- (sys.west);
  \draw[->] (sys.east) -- (3,0);

  \node[above,green!60!black] at (-2.5,0) {Input};
  \node[below] at (-2.5,0) {$x(t)$};
  \node[above,green!60!black] at (2.5,0) {Output};
  \node[below] at (2.5,0) {$y(t)$};
\end{tikzpicture}
```
:::

::: {.column style="color:magenta;"}
&nbsp; Classical control theory (root locus, Bode plot)
:::
::::

### 3 properties {-}

$\color{RedOrange}\boxed{\textbf{Homogeneity}}$

::: {layout-ncol=2}
\begin{equation}
\underset{\quad\quad\quad \color{magenta} {}^{\uparrow_{\hspace{-3pt}\_\_\_}}\,\,\text{scaling factor}}
{\begin{array}{rcl}
\text{if} \quad x & \rightarrow & y \\
\text{then} \quad 2x & \rightarrow & 2y \\
\color{magenta}a \color{black} \,x & \rightarrow & \color{magenta}a \color{black} \,y
\end{array}}
\end{equation}

\begin{array}{rcll}
\color{ForestGreen} \text{E.g.}\quad\text{Is}\quad y & \color{ForestGreen} = & \color{ForestGreen} 3x+1 & \color{ForestGreen} \text{LTI ?} \\
\color{blue} 4 & & \color{blue} 1 & \\
\color{blue} 7 & & \color{blue} 2 & \color{Magenta}\text{NO} \\
\color{blue} 10 & & \color{blue} 3 & \\[2ex]
\color{ForestGreen} \text{Is}\quad y & \color{ForestGreen} = & \color{ForestGreen} 3x & \color{ForestGreen} \text{LTI ?} \\
\color{blue} 3 & & \color{blue} 1 & \\
\color{blue} 6 & & \color{blue} 2 & \color{Magenta}\text{YES} \\
\end{array}
:::

:::: {.columns}
::: {.column style="text-align:right"}
```{.tikz}
\begin{tikzpicture}[
    >=latex,
    axis/.style={->, black}
]
    \draw[axis] (-0.5,0) -- (3,0) node[right] {$x$};
    \draw[axis] (0,-0.5) -- (0,5) node[above] {$y$};

    \draw[domain=-0.5:1.5, samples=100, smooth, thick, orange!80!black] plot (\x, {3*\x+1});
    \node[right,orange!80!black] at (1.2,4.5) {$y=3x+1$};
    \node[left,orange!80!black] at (0,1) {$1$};
    \draw[orange!80!black] (0,1) -- (0.1,1);
    \draw[green!60!black,dashed] (0.8,0) -- (0.8,3.4);
    \node[below,green!60!black] at (0.8,0) {$x$};
    \node[left,green!60!black] at (0,3.4) {$y$};
    \draw[green!60!black,dashed] (0,3.4) -- (0.8,3.4);
    \draw[orange!60!red,dashed] (1,0) -- (1,4);
    \draw[orange!60!red,dashed] (0,4) -- (1,4);
    \draw[->,orange!60!red,thick] (0.8,0.8) -- (1.05,0.8);
    \node[right,orange!60!red] at (1,0.8) {$\Delta x$};
    \draw[->,orange!60!red,thick] (0.4,3.4) -- (0.4,4.05);
    \node[above,orange!60!red] at (0.4,4) {$\Delta y$};
\end{tikzpicture}
```
&nbsp;
:::

::: {.column}
small-signal modeling:
\begin{align*}
    \color{RedOrange} Y + \Delta y \,&\color{RedOrange}= 3(X + \Delta x) + 1 \\
    \color{magenta}\underline{\color{RedOrange} Y} \color{RedOrange} + \Delta y \,&\color{RedOrange}= \color{magenta}\underline{\color{RedOrange} 3X} \color{RedOrange} + 3\Delta x + \color{magenta}\underline{\color{RedOrange}1} \\
    \color{RedOrange} \Delta y \,&\color{RedOrange}= 3\Delta x 
\end{align*}
:::

::: {.column style="text-align:right"}
```{.tikz}
\begin{tikzpicture}[
    >=latex,
    axis/.style={->, black}
]
    \draw[axis] (-0.5,0) -- (3,0) node[right] {$x$};
    \draw[axis] (0,-0.5) -- (0,5) node[above] {$y$};

    \draw[domain=0:2, samples=100, smooth, thick, orange!80!black] plot (\x, {(\x)^2});
    \draw[domain=0.5:1.3, samples=100, smooth, thick, magenta] plot (\x, {1.6*(\x-0.8)+0.64});
    \node[right,orange!80!black] at (1.5,2) {$y=x^2$};
    \node[below,green!60!black] at (0.8,0) {$x$};
    \node[left,green!60!black] at (0,0.64) {$y$};
    \draw[green!60!black,dashed] (0.8,0) -- (0.8,0.64);
    \draw[green!60!black,dashed] (0,0.64) -- (0.8,0.64);
    \draw[orange!60!red,dashed] (1,0) -- (1,1);
    \draw[orange!60!red,dashed] (0,1) -- (1,1);
    \draw[->,orange!60!red,thick] (0.8,0.4) -- (1.05,0.4);
    \node[right,orange!60!red] at (1,0.4) {$\Delta x$};
    \draw[->,orange!60!red,thick] (0.4,0.64) -- (0.4,1);
    \node[above,orange!60!red] at (0.4,1) {$\Delta y$};
\end{tikzpicture}
```
&nbsp;
:::

::: {.column}
small-signal modeling:
\usepackage{cancel}
\begin{align*}
    \color{RedOrange} Y + \Delta y \,&\color{RedOrange}= (X + \Delta x)^2 \\
    \color{magenta}\underline{\color{RedOrange} Y} \color{RedOrange} + \Delta y \,&\color{RedOrange}= \color{magenta}\underline{\color{RedOrange} X^2} \color{RedOrange} + 2X \cdot \Delta x + \color{magenta}\cancel{\color{RedOrange} \Delta x^2} \quad \text{for small }\Delta x \\
    \color{RedOrange} \Delta y \,&\color{RedOrange}= \color{magenta}\underset{\displaystyle\frac{dy}{dx}\bigg\rvert_{x=X}}{\underset{\uparrow}{\underline{{\color{RedOrange} 2X}}}} \color{RedOrange} \cdot \Delta x 
\end{align*}
:::

::: {.column style="text-align:right"}
```{.tikz}
\begin{tikzpicture}[
    >=latex,
    axis/.style={->, black}
]
    \draw[axis] (-0.5,0) -- (3,0) node[right] {$x$};
    \draw[axis] (0,-0.5) -- (0,5) node[above] {$y$};

    \draw[domain=-0.5:1.5, samples=100, smooth, thick, orange!80!black] plot (\x, {exp(\x)});
    \draw[domain=0.5:1.3, samples=100, smooth, thick, magenta] plot (\x, {exp(0.8)*(\x-0.8)+exp(0.8)});
    \node[right,orange!80!black] at (1.5,4) {$y=e^x$};
    \node[below,green!60!black] at (0.8,0) {$x$};
    \node[left,green!60!black] at (0,{exp(0.8)}) {$y$};
    \draw[green!60!black,dashed] (0.8,0) -- (0.8,{exp(0.8)});
    \draw[green!60!black,dashed] (0.8,{exp(0.8)}) -- (0,{(exp(0.8});
    \draw[orange!60!red,dashed] (1,0) -- (1,{exp(1)});
    \draw[orange!60!red,dashed] (0,{exp(1)}) -- (1,{exp(1)});
    \draw[->,orange!60!red,thick] (0.8,0.8) -- (1.05,0.8);
    \node[right,orange!60!red] at (1,0.8) {$\Delta x$};
    \draw[->,orange!60!red,thick] (0.4,{exp(0.8)}) -- (0.4,{exp(1)});
    \node[above,orange!60!red] at (0.4,{exp(1)}) {$\Delta y$};
\end{tikzpicture}
```
&nbsp;
:::

::: {.column}
small-signal modeling:
\usepackage{cancel}
\begin{align*}
    \color{RedOrange} \Delta y \,&\color{RedOrange}= e^X \cdot \Delta x
\end{align*}
:::
::::

$\color{RedOrange}\boxed{\textbf{Superposition}}$

\begin{array}{lrcl}
\text{if} & x_1 & \rightarrow & y_1, \\
& x_2 & \rightarrow & y_2 \\
\text{then} & (x_1+x_2) & \rightarrow & (y_1+y_2)
\end{array}

$\color{RedOrange}\boxed{\textbf{Time Translation}}$

\begin{array}{lrcl}
\text{if} & x(t) & \rightarrow & y(t), \\
\text{then} & x(t-\tau) & \rightarrow & y(t-\tau)
\end{array}

::: {style="color:green"}
E.g. Unit impulse response

```{.tikz}
\begin{tikzpicture}[>=latex, thick]
\begin{scope}
    \node[draw, minimum width=2.2cm, minimum height=1cm,green!60!black] (sys) {$LTI$};
    
    \draw[->,green!60!black] (-2.5,0) -- (sys.west);
    \draw[->,green!60!black] (sys.east) -- (2.5,0);
    
    \node[above] at (-2.5,0) {$x(t) = \color{blue} \delta(t)$};
    \node[above] at (2.5,0) {$y(t) = \color{blue} h(t)$};
\end{scope}
\begin{scope}[xshift=5cm]
    % ground line
    \draw (0,0) -- (5,0);
    % ground hatching
    \foreach \x in {1,2,...,10} {
        \draw ({\x/2-0.5},-0.25) -- ({\x/2-0.2},0);
    }
    % block mass
    \draw (2.5,0.05) rectangle (3.7,0.85);
    \node at (3.1,0.45) {$m$};
    % hammer
    \draw (1.6,0.35) -- (2.4,0.35) -- (2.4,0.65)
       -- (2.1,0.65) -- (2.1,1.80) -- (1.9,1.80)
       -- (1.9,0.65) -- (1.6,0.65) -- (1.6,0.35);
    \draw (2.3,0.65) -- (2.2,0.95) -- (2.3,0.85)
       -- (2.3,1.10) -- (2.4,1.00) -- (2.4,1.25)
       -- (2.5,1.15) -- (2.55,1.35) -- (2.6,1.15)
       -- (2.7,1.25) -- (2.7,1.00) -- (2.8,1.10)
       -- (2.8,0.85);
\end{scope}
\begin{scope}[xshift=-3cm,yshift=-4cm]
    \draw[thin,->] (0,0) -- (2.5,0) node[right] {$t$};
    \draw[thin,->] (0,0) -- (0,2) node[right] {$x(t)$};
    \draw[->,blue] (0,0) -- (0,1);
    \draw[->,magenta] (1,0) -- (1,1);
    \node[right,blue] at (0,1.2) {$\delta(t)=$ Force};
    \node[right,magenta] at (1,0.75) {$\delta(t-1)$};
    \node[below,blue] at (0,0) {$0$};
    \node[below,magenta] at (1,0) {$1$};
\end{scope}
\begin{scope}[xshift=2cm,yshift=-4cm]
    \draw[thin,->] (0,0) -- (3.5,0) node[right] {$t$};
    \draw[thin,->] (0,0) -- (0,2) node[right] {$y(t)$};
    \draw[domain=0:2,samples=100,smooth,blue,thick] plot (\x, {1.15*exp(-\x)-1.15*exp(-2)});
    \draw[magenta,thick] (1,0) -- (1,1);
    \draw[domain=1:3,samples=100,smooth,magenta,thick] plot (\x, {1.15*exp(-\x+1)-1.15*exp(-2)});
    \node[right,blue] at (0,1.2) {$h(t)=$ speed};
    \node[right,magenta] at (1.5,0.75) {$h(t-1)$};
    \node[below,blue] at (0,0) {$0$};
    \node[below,magenta] at (1,0) {$1$};
\end{scope}
\end{tikzpicture}
```
:::

## Convolution

\begin{equation}
    h(t) * x(t) = \int_{-\infty}^{\infty} x(\tau)h(t-\tau) \,d\tau
\end{equation}

::: {style="text-align:center"}
```{.tikz}
\begin{tikzpicture}[>=latex, thick]
  \node[draw, minimum width=2.2cm, minimum height=1cm] (sys) {$LTI$};

  \draw[->] (-3,0) -- (sys.west);
  \draw[->] (sys.east) -- (3,0);

  \node[above] at (-2.5,0) {$x(t)$};
  \node[above] at (2.5,0) {$y(t)=x(t) * h(t)$};
  \node[below] at (sys.south) {$h(t)$};
\end{tikzpicture}
```
:::

where $h(t)$ is the unit impulse response: $\begin{cases}\text{when } x(t) = \delta(t)\\\text{then } y(t) = h(t)\end{cases}$

```{.tikz}
\begin{tikzpicture}[
    >=latex,
    axis/.style={->, black}
]

\begin{scope}
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$x(t)$};
    \draw[->,blue,thick] (0,0) -- (0,1);
    \node[right,blue] at (0,1) {$\delta(t)$};
\end{scope}

\begin{scope}[xshift=6cm]
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$y(t)$};
    \draw[domain=0:2, thick, blue] plot (\x, {exp(-\x)-exp(-2)});
    \node[right,blue] at (0.5,0.7) {$h(t)$};
\end{scope}

\begin{scope}[yshift=-3.5cm]
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$x(t)$};
    \draw[->,blue,thick] (0,0) -- (0,2);
    \node[right,blue] at (0,2) {$2\delta(t)$};
\end{scope}

\begin{scope}[xshift=6cm,yshift=-3.5cm]
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$y(t)$};
    \draw[domain=0:2, thick, blue] plot (\x, {2*exp(-\x)-2*exp(-2)});
    \node[right,blue] at (0.5,1.2) {$2h(t)$};
\end{scope}

\begin{scope}[yshift=-7cm]
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$x(t)$};
    \draw[->,blue,thick] (2,0) -- (2,1);
    \node[right,blue] at (2,1) {$\delta(t-2)$};
\end{scope}

\begin{scope}[xshift=6cm,yshift=-7cm]
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$y(t)$};
    \draw[thick,blue] (2,0) -- (2,{1-exp(-2)});
    \draw[domain=2:4, thick, blue] plot (\x, {exp(-\x+2)-exp(-2)});
    \node[right,blue] at (2.5,0.7) {$h(t-2)$};
\end{scope}

\begin{scope}[yshift=-10.5cm]
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$x(t)$};
    \draw[->,blue,thick] (0,0) -- (0,1);
    \draw[->,blue,thick] (1,0) -- (1,1);
    \draw[->,blue,thick] (2,0) -- (2,1);
    \node[left,blue] at (0,1) {$\delta(t)$};
    \node[above,blue] at (1,1) {$\delta(t-1)$};
    \node[right,blue] at (2,1) {$\delta(t-2)$};
\end{scope}

\begin{scope}[xshift=6cm,yshift=-10.5cm]
    \draw[axis] (0,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,0) -- (0,2.2) node[above] {$y(t)$};
    
    \draw[domain=0:1, thick, blue] plot (\x, {exp(-\x)-exp(-2)});
    \draw[domain=1:2, dashed, thick, blue] plot (\x, {exp(-\x)-exp(-2)});
    
    \draw[domain=1:2, thick, blue] plot (\x, {exp(-\x)-exp(-2)+exp(-\x+1)-exp(-2)});
    \draw[domain=1:3, dashed, thick, blue] plot (\x, {exp(-\x+1)-exp(-2)});
    
    \draw[domain=2:3, thick, blue] plot (\x, {exp(-\x+1)-exp(-2)+exp(-\x+2)-exp(-2)});
    \draw[domain=3:4, thick, blue] plot (\x, {exp(-\x+2)-exp(-2)});
    \draw[domain=2:4, dashed, thick, blue] plot (\x, {exp(-\x+2)-exp(-2)});
    
    \draw[thick,blue] (1,{exp(-1)-exp(-2)}) -- (1,{1+exp(-1)-2*exp(-2)});
    \draw[thick,blue] (2,{exp(-1)-exp(-2)}) -- (2,{1+exp(-1)-2*exp(-2)});
    \node[right,violet] at (2,1.5) {$y(t)=h(t)+h(t-1)+h(t-2)$};
\end{scope}
\end{tikzpicture}
```

$$ \int_{-\infty}^{\infty} h(t) \,dt = 1.  \qquad y(t) = \delta(0) \cdot h(t) + \delta(1) \cdot h(t-1) + \delta(2) \cdot h(t-2) .$$

For LTI system, $y(t)$ is the sum of the scaled unit impulse response of $x(t)$ at each time instant $\tau$.
$$y(t) = \int_{-\infty}^{\infty} x(\tau)h(t-\tau) \,d\tau$$
where $x(\tau)$ is the scaling factor at $t=\tau$, and $h(t-\tau)$ is the unit impulse response at $t=\tau$.

For a continuous $x(t)$ with $h(t) = \dfrac{1}{2}t$, ($0 \le t \le 2$), what is $y(t)$?

::: {style="text-align:center"}
```{.tikz}
\begin{tikzpicture}[
    >=latex,
    axis/.style={->, black}
]
\begin{scope}
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$x(t)$};
    \draw[orange!80!black,thick] (0,0) -- (0,1);
    \draw[orange!80!black,thick] (0,1) -- (2,1);
    \draw[orange!80!black,thick] (2,1) -- (2,0);
    \draw[orange!80!black,dashed,thick] (1,1) -- (1,0);
    \node[orange!80!black] at (-0.2,1) {$1$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
\end{scope}
\node[scale=2] at (3.5,1) {$\ast$};
\node[scale=2] at (8,1) {$=$};
\node[scale=2] at (3.5,-2.5) {$\ast$};
\node[scale=2] at (8,-2.5) {$=$};
\node[scale=2] at (3.5,-6) {$\ast$};
\node[scale=2] at (8,-6) {$=$};
\node[scale=2] at (3.5,-9.5) {$\ast$};
\node[scale=2] at (8,-9.5) {$=$};
\begin{scope}[xshift=4.5cm]
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$h(t)$};
    \draw[orange!80!black,thick] (0,0) -- (2,1);
    \draw[orange!80!black,thick] (2,1) -- (2,0);
    \draw[orange!80!black,dashed,thick] (0,1) -- (2,1);
    \draw[orange!80!black,thick] (1,0.1) -- (1,0);
    \node[orange!80!black] at (-0.2,1) {$1$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
\end{scope}
\begin{scope}[xshift=9cm]
    \draw[axis] (-0.2,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$y(t)$};
    \node[scale=2,magenta] at (2,1) {?};
\end{scope}

\begin{scope}[yshift=-3.5cm]
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$x(t)$};
    \draw[orange!80!black,thick,->] (0,0) -- (0,1.5);
    \draw[orange!80!black,thick,->] (1,0) -- (1,1.5);
    \node[orange!80!black,right] at (0,1.5) {$\delta(t)$};
    \node[orange!80!black,right] at (1,1.5) {$\delta(t-1)$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
    \draw[orange!80!black] (2,0) -- (2,0.1);
\end{scope}
\begin{scope}[xshift=4.5cm,yshift=-3.5cm]
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$h(t)$};
    \draw[orange!80!black,thick] (0,0) -- (2,1);
    \draw[orange!80!black,thick] (2,1) -- (2,0);
    \draw[orange!80!black,dashed,thick] (0,1) -- (2,1);
    \draw[orange!80!black,thick] (1,0.1) -- (1,0);
    \node[orange!80!black] at (-0.2,1) {$1$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
\end{scope}
\begin{scope}[xshift=9cm,yshift=-3.5cm]
    \draw[axis] (-0.2,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$y(t)$};
    \draw[magenta,thick] (0,0) -- (1,0.5);
    \draw[magenta,thick,dashed] (1,0.5) -- (2,1);
    \draw[magenta,thick] (1,0.5) -- (2,1.5);
    \draw[magenta,thick] (2,1.5) -- (2,0.5);
    \draw[magenta,thick] (2,0.5) -- (3,1);
    \draw[magenta,thick] (3,1) -- (3,0);
    \node[magenta] at (-0.2,-0.2) {$0$};
    \node[magenta] at (1,-0.2) {$1$};
    \node[magenta] at (2,-0.2) {$2$};
    \node[magenta] at (3,-0.2) {$3$};
    \foreach \x in {1,2,3} {
        \draw[magenta] (\x,0) -- (\x,0.1);
    }
\end{scope}

\begin{scope}[yshift=-7cm]
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$x(t)$};
    \draw[orange!80!black,thick,->] (0,0) -- (0,0.75);
    \draw[orange!80!black,thick,->] (0.5,0) -- (0.5,0.75);
    \draw[orange!80!black,thick,->] (1,0) -- (1,0.75);
    \draw[orange!80!black,thick,->] (1.5,0) -- (1.5,0.75);
    \node[orange!80!black] at (-0.3,0.75) {$\frac{1}{2}\delta$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
    \draw[orange!80!black] (2,0) -- (2,0.1);
\end{scope}
\begin{scope}[xshift=4.5cm,yshift=-7cm]
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$h(t)$};
    \draw[orange!80!black,thick] (0,0) -- (2,1);
    \draw[orange!80!black,thick] (2,1) -- (2,0);
    \draw[orange!80!black,dashed,thick] (0,1) -- (2,1);
    \draw[orange!80!black,thick] (1,0.1) -- (1,0);
    \node[orange!80!black] at (-0.2,1) {$1$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
\end{scope}
\begin{scope}[xshift=9cm,yshift=-7cm]
    \draw[axis] (-0.2,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$y(t)$};
    \draw[magenta,thick] (0,0) -- (0.5,0.125)
                               -- (1,0.375)
                               -- (1.5,0.75)
                               -- (2.0,1.250) -- (2.0,0.75)
                               -- (2.5,1.125) -- (2.5,0.625)
                               -- (3.0,0.875) -- (3.0,0.375)
                               -- (3.5,0.5) -- (3.5,0);
    \node[magenta] at (-0.2,-0.2) {$0$};
    \node[magenta] at (1,-0.2) {$1$};
    \node[magenta] at (2,-0.2) {$2$};
    \node[magenta] at (3,-0.2) {$3$};
    \node[magenta] at (4,-0.2) {$4$};
    \foreach \x in {1,2,3,4} {
        \draw[magenta] (\x,0) -- (\x,0.1);
    }
\end{scope}

\begin{scope}[yshift=-10.5cm]
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$x(t)$};
    \foreach \x in {0,0.1,...,2} {
        \draw[orange!80!black,thick,->] (\x,0) -- (\x,0.25);
    }
    \node[orange!80!black] at (-0.3,0.3) {$\frac{1}{n}\delta$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
    \draw[orange!80!black] (2,0) -- (2,0.1);
\end{scope}
\begin{scope}[xshift=4.5cm,yshift=-10.5cm]
    \draw[axis] (-0.2,0) -- (3,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$h(t)$};
    \draw[orange!80!black,thick] (0,0) -- (2,1);
    \draw[orange!80!black,thick] (2,1) -- (2,0);
    \draw[orange!80!black,dashed,thick] (0,1) -- (2,1);
    \draw[orange!80!black,thick] (1,0.1) -- (1,0);
    \node[orange!80!black] at (-0.2,1) {$1$};
    \node[orange!80!black] at (-0.2,-0.2) {$0$};
    \node[orange!80!black] at (1,-0.2) {$1$};
    \node[orange!80!black] at (2,-0.2) {$2$};
\end{scope}
\begin{scope}[xshift=9cm,yshift=-10.5cm]
    \draw[axis] (-0.2,0) -- (4.2,0) node[right] {$t$};
    \draw[axis] (0,-0.2) -- (0,2) node[above] {$y(t)$};
    \foreach \x in {0,0.1,...,2} {
        \draw[magenta,thick] (\x,{\x*(\x*10+1)/40}) -- ({\x+0.1},{(\x+0.1)*(\x*10+2)/40});
    }
    \foreach \x in {2,2.1,...,4} {
        \draw[magenta,thick] (\x,{(0.95+(\x-2)/2)*(40-\x*10)/20}) -- ({\x+0.1},{(1+(\x+0.1-2)/2)*(40-\x*10)/20});
        \draw[magenta,thick] (\x,{(0.95+(\x-2)/2)*(40-\x*10)/20}) -- (\x,{(0.95+(\x-2)/2)*(40-\x*10)/20+0.1});
    }
    \draw[magenta,thick] (4,0) -- (4,0.1);
    \node[magenta] at (-0.2,-0.2) {$0$};
    \node[magenta] at (1,-0.2) {$1$};
    \node[magenta] at (2,-0.2) {$2$};
    \node[magenta] at (3,-0.2) {$3$};
    \node[magenta] at (4,-0.2) {$4$};
    \foreach \x in {1,2,3,4} {
        \draw[magenta] (\x,0) -- (\x,0.1);
    }
\end{scope}
\end{tikzpicture}
```
&nbsp;
:::

Time domain convolution compuation is expensive, and it can be simplified by using Fourier transform to transfer **convolution** in *time domain* to **multiplication** in *frequency domain*.

$$\text{Time domain} \underset{\text{F. T.}}{\overset{\text{Fourier Transform}}{\longrightarrow}} \text{Frequency domain}$$

$$\text{F. T.:}\quad Y(\omega) = \int_{-\infty}^{\infty} y(t) e^{-j\omega t} \,dt$$

*Proof*: $\mathcal{F}[f(t) * g(t)] = F(\omega) \cdot G(\omega)$.

\begin{align*}
\mathcal{F}[f(t) * g(t)] &= \int_{-\infty}^{\infty} \left(\int_{-\infty}^{\infty} f(\tau)g(t-\tau) \,d\tau\right) \cdot e^{-j\omega t} \,dt \\
&= \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} f(\tau) \cdot g(t-\tau) \cdot e^{-j\omega t} \,d\tau dt \\
&= \int_{-\infty}^{\infty} f(\tau) \left( \int_{-\infty}^{\infty} g(t-\tau) e^{-j\omega t} \,dt \right) d\tau \\
&= \int_{-\infty}^{\infty} f(\tau) \cdot e^{-j\omega \tau} \cdot G(\omega) \,d\tau \tag{see note below} \\
&= G(\omega) \cdot \int_{-\infty}^{\infty} f(\tau) e^{-j\omega \tau} \,d\tau \\
&= F(\omega) \cdot G(\omega)
\end{align*}
 
Note that:
\begin{align*}
    \mathcal{F}[g(t)] &= G(\omega) \\
    \mathcal{F}[g(t-\tau)] &= \int_{-\infty}^{\infty} g(t-\tau) e^{-j\omega t} \,dt \\
    &= \int_{-\infty}^{\infty} g(t-\tau) e^{-j\omega (t-\tau)} \,dt \cdot e^{-j\omega \tau} \\
    &= \int_{-\infty}^{\infty} g(u) e^{-j\omega u} \,du \cdot e^{-j\omega \tau} \tag{let $u = t-\tau$} \\
    &= e^{-j\omega \tau} \cdot G(\omega)
\end{align*}
