project:
  type: book
  output-dir: docs

book:
  title: "EE6653 - Power Electronics Notes"
  author: "Qiaoxuan Zhang"
  date: "5/6/2026"
  chapters:
    - index.qmd
    - 1_convolution.qmd
    - 2_fourier_transform.qmd
    - 3_laplace_transform.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    page-layout: full
    mathjax: true
    highlight: true
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

filters:
  - diagram




