project:
  type: book
  output-dir: docs

book:
  title: "EE6653 - Power Electronics Notes"
  author: "Qiaoxuan Zhang"
  date: "5/6/2026"
  chapters:
    - index.qmd
    - 1_convolution.qmd
    - 2_fourier_transform.qmd
    - 3_laplace_transform.qmd
    - 4_time-domain_response.qmd
    - 5_frequency_response.qmd
    # - references.qmd
  page-footer: 
    left: "EE6653 - Power Electronics, taught by Prof. Shuang Xu, UNB" 
    right: 
      - icon: github
        href: https://github.com/q30zhang/EE6653_notes

bibliography: references.bib

format:
  html:
    page-layout: full
    mathjax: true
    highlight: true
    theme:
      - cosmo
      - brand

filters:
  - diagram




